language: node_js

node_js:
  - "8.11.3"

addons:
  firefox: latest

before_script:
- cp config/server-dev.json config/server.json
- npx db-migrate up
- npm run start &> server.log &
- echo $! > server.pid
- cat server.pid
- node helper.js wait-for-server

script:
- npm run lint
- npm run test-cafe-headless

after_script:
- kill $(cat server.pid)
- echo 'finished'
- cat server.log

cache:
  directories:
  - "node_modules"
