language: node_js

node_js:
  - "8.11.3"

addons:
  chrome: stable

before_script:
- cp config/server-dev.json config/server.json
- npx db-migrate up
- npm run start

script:
- npm run test-cafe-headless

cache:
  directories:
  - "node_modules"
