:toc:

Project to discover different ways for a node-server application.



== Problem domain ==

An organisation wants to support different stations with parcels from 
a main station.

== Start ==

Steps to start the app.

[source,bash]
----
nvm use 8
npm install
npx db-migrate up        # create database (development)
node helper.js user-add  # add user for login

npm start                # start the app
----


== help ==

=== helper ===

you can execute the helper program with ```node helper.js```

[source,bash]
----
node helper.js user
node helper.js user-add
node helper.js user-del <username>
----

=== Express-Middleware ===

* http://expressjs.com/en/resources/middleware.html

=== db-migrate ===

* https://kostasbariotis.com/data-migration-with-nodejs/
* https://db-migrate.readthedocs.io/en/latest/

[source,bash]
----
# options
# --env
# --env dev  -> development db (default)
# --env prod -> productive db

npx db-migrate                  # show help
npx db-migrate db:create test   # create db (in dev)
npx db-migrate create $description-without-space
npx db-migrate create create-table-movies # create new script
npx db-migrate up               # migrate
npx db-migrate down             # rollback
----

=== sqlite ===

There is no special data type for Date. But if it is formatted as ISO8601-string ("YYYY-MM-DD HH:MM:SS.SSS") than it will be handled as DATE.

There is no special data type for BOOLEAN so INTEGER is used with values 1 and 0

=== HTTPS ===

* self-signed or letsEncrypt

==== create self-signed certificate ====

[source,bash]
----
mkdir cert
cd cert
openssl genrsa -out localhost.key 2048
openssl req -new -x509 -key localhost.key -out localhost.cert -days 9999 -subj '/CN=localhost'
cd ..
----

=== Config ===

A config example you can find under ```config/server-example.json``` you can copy this to ```config/server.json``` and adjust the values to your need. All possible configs should be shown in the example.


=== docker ===

[source,bash]
----
docker build -t cutl/parcel-tracking .
docker run -p 8080:8080 -v $(pwd)/parcel.db:/usr/src/app/parcel.db --name parcelTracking -d cutl/parcel-tracking
docker run -p 8080:8080 -v $(pwd)/parcel.db:/usr/src/app/parcel.db -it cutl/parcel-tracking bash

# get ip
sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' parcelTracking

# free space
docker stop parcelTracking
docker rm parcelTracking
docker images -a
docker rmi cutl/parcel-tracking -f
docker images purge
# remove every image
docker system prune -a
----

=== nginx ===

Proxy config is not nice at the moment but working with the following rules.

TODO is that all the sub_filters are not needed any longer.

----
    location /parcelTracking/ {
        proxy_pass http://172.17.0.7:8080/;
        proxy_redirect ~/(.*)$ /parcelTracking/$1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;

        sub_filter "href=\"/" "href=\"/parcelTracking/";
        sub_filter "src=\"/" "src=\"/parcelTracking/";
        sub_filter "action=\"/" "action=\"/parcelTracking/";
        sub_filter_once off;
    }
----